// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Alerte struct {
	ID             int64      `json:"id"`
	CameraID       *int64     `json:"camera_id"`
	ZoneID         *int64     `json:"zone_id"`
	TypeRisqueID   *int64     `json:"type_risque_id"`
	Severite       int64      `json:"severite"`
	Description    string     `json:"description"`
	DetailsIa      *string    `json:"details_ia"`
	Confiance      float64    `json:"confiance"`
	ImageUrl       *string    `json:"image_url"`
	VideoClipUrl   *string    `json:"video_clip_url"`
	Statut         string     `json:"statut"`
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	AcknowledgedBy *string    `json:"acknowledged_by"`
	ResolvedAt     *time.Time `json:"resolved_at"`
	ResolvedBy     *string    `json:"resolved_by"`
	Notes          *string    `json:"notes"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Camera struct {
	ID                int64      `json:"id"`
	Nom               string     `json:"nom"`
	ZoneID            *int64     `json:"zone_id"`
	Emplacement       *string    `json:"emplacement"`
	FluxUrl           *string    `json:"flux_url"`
	Statut            string     `json:"statut"`
	DerniereDetection *time.Time `json:"derniere_detection"`
	CreatedAt         time.Time  `json:"created_at"`
}

type Detection struct {
	ID        int64     `json:"id"`
	CameraID  *int64    `json:"camera_id"`
	TypeObjet string    `json:"type_objet"`
	Confiance float64   `json:"confiance"`
	Bbox      *string   `json:"bbox"`
	Attributs *string   `json:"attributs"`
	CreatedAt time.Time `json:"created_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type StatsPeriode struct {
	ID                int64     `json:"id"`
	Date              time.Time `json:"date"`
	ZoneID            *int64    `json:"zone_id"`
	NbAlertes         int64     `json:"nb_alertes"`
	NbDetections      int64     `json:"nb_detections"`
	NbPersonnesMax    int64     `json:"nb_personnes_max"`
	TauxConformiteEpi *float64  `json:"taux_conformite_epi"`
	IncidentsEvites   int64     `json:"incidents_evites"`
	CreatedAt         time.Time `json:"created_at"`
}

type TypesRisque struct {
	ID          int64   `json:"id"`
	Code        string  `json:"code"`
	Nom         string  `json:"nom"`
	Description *string `json:"description"`
	Severite    int64   `json:"severite"`
	Couleur     string  `json:"couleur"`
	Icone       *string `json:"icone"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}

type Zone struct {
	ID           int64     `json:"id"`
	Nom          string    `json:"nom"`
	Description  *string   `json:"description"`
	NiveauRisque string    `json:"niveau_risque"`
	Coordonnees  *string   `json:"coordonnees"`
	CreatedAt    time.Time `json:"created_at"`
}
