// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: securite.sql

package dbgen

import (
	"context"
	"time"
)

const acknowledgeAlerte = `-- name: AcknowledgeAlerte :exec
UPDATE alertes SET statut = 'acknowledged', acknowledged_at = ? WHERE id = ?
`

type AcknowledgeAlerteParams struct {
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	ID             int64      `json:"id"`
}

func (q *Queries) AcknowledgeAlerte(ctx context.Context, arg AcknowledgeAlerteParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAlerte, arg.AcknowledgedAt, arg.ID)
	return err
}

const countActiveAlertes = `-- name: CountActiveAlertes :one
SELECT COUNT(*) FROM alertes WHERE statut = 'active'
`

func (q *Queries) CountActiveAlertes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAlertes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCameras = `-- name: CountActiveCameras :one
SELECT COUNT(*) FROM cameras WHERE statut = 'active'
`

func (q *Queries) CountActiveCameras(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCameras)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertesToday = `-- name: CountAlertesToday :one
SELECT COUNT(*) FROM alertes WHERE date(created_at) = date('now')
`

func (q *Queries) CountAlertesToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlertesToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHighRiskZones = `-- name: CountHighRiskZones :one
SELECT COUNT(*) FROM zones WHERE niveau_risque IN ('eleve', 'critique')
`

func (q *Queries) CountHighRiskZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHighRiskZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAlertesParJour = `-- name: GetAlertesParJour :many
SELECT 
    date(created_at) as jour,
    COUNT(*) as total,
    SUM(CASE WHEN severite >= 8 THEN 1 ELSE 0 END) as critiques,
    SUM(CASE WHEN severite >= 5 AND severite < 8 THEN 1 ELSE 0 END) as moyennes,
    SUM(CASE WHEN severite < 5 THEN 1 ELSE 0 END) as faibles
FROM alertes
WHERE created_at >= date('now', '-7 days')
GROUP BY date(created_at)
ORDER BY jour
`

type GetAlertesParJourRow struct {
	Jour      interface{} `json:"jour"`
	Total     int64       `json:"total"`
	Critiques *float64    `json:"critiques"`
	Moyennes  *float64    `json:"moyennes"`
	Faibles   *float64    `json:"faibles"`
}

func (q *Queries) GetAlertesParJour(ctx context.Context) ([]GetAlertesParJourRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlertesParJour)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAlertesParJourRow{}
	for rows.Next() {
		var i GetAlertesParJourRow
		if err := rows.Scan(
			&i.Jour,
			&i.Total,
			&i.Critiques,
			&i.Moyennes,
			&i.Faibles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertesParType = `-- name: GetAlertesParType :many
SELECT 
    tr.code,
    tr.nom,
    tr.couleur,
    COUNT(*) as total
FROM alertes a
JOIN types_risque tr ON a.type_risque_id = tr.id
WHERE a.created_at >= date('now', '-30 days')
GROUP BY tr.id
ORDER BY total DESC
`

type GetAlertesParTypeRow struct {
	Code    string `json:"code"`
	Nom     string `json:"nom"`
	Couleur string `json:"couleur"`
	Total   int64  `json:"total"`
}

func (q *Queries) GetAlertesParType(ctx context.Context) ([]GetAlertesParTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlertesParType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAlertesParTypeRow{}
	for rows.Next() {
		var i GetAlertesParTypeRow
		if err := rows.Scan(
			&i.Code,
			&i.Nom,
			&i.Couleur,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTypesRisque = `-- name: GetTypesRisque :many
SELECT id, code, nom, description, severite, couleur, icone FROM types_risque ORDER BY severite DESC
`

func (q *Queries) GetTypesRisque(ctx context.Context) ([]TypesRisque, error) {
	rows, err := q.db.QueryContext(ctx, getTypesRisque)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TypesRisque{}
	for rows.Next() {
		var i TypesRisque
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Nom,
			&i.Description,
			&i.Severite,
			&i.Couleur,
			&i.Icone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAlertes = `-- name: ListActiveAlertes :many
SELECT 
    a.id,
    a.camera_id,
    c.nom as camera_nom,
    a.zone_id,
    z.nom as zone_nom,
    a.type_risque_id,
    tr.code as type_risque_code,
    tr.nom as type_risque_nom,
    tr.couleur as type_risque_couleur,
    a.severite,
    a.description,
    a.details_ia,
    a.confiance,
    a.image_url,
    a.statut,
    a.created_at
FROM alertes a
LEFT JOIN cameras c ON a.camera_id = c.id
LEFT JOIN zones z ON a.zone_id = z.id
LEFT JOIN types_risque tr ON a.type_risque_id = tr.id
WHERE a.statut = 'active'
ORDER BY a.severite DESC, a.created_at DESC
`

type ListActiveAlertesRow struct {
	ID                int64     `json:"id"`
	CameraID          *int64    `json:"camera_id"`
	CameraNom         *string   `json:"camera_nom"`
	ZoneID            *int64    `json:"zone_id"`
	ZoneNom           *string   `json:"zone_nom"`
	TypeRisqueID      *int64    `json:"type_risque_id"`
	TypeRisqueCode    *string   `json:"type_risque_code"`
	TypeRisqueNom     *string   `json:"type_risque_nom"`
	TypeRisqueCouleur *string   `json:"type_risque_couleur"`
	Severite          int64     `json:"severite"`
	Description       string    `json:"description"`
	DetailsIa         *string   `json:"details_ia"`
	Confiance         float64   `json:"confiance"`
	ImageUrl          *string   `json:"image_url"`
	Statut            string    `json:"statut"`
	CreatedAt         time.Time `json:"created_at"`
}

func (q *Queries) ListActiveAlertes(ctx context.Context) ([]ListActiveAlertesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlertes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertesRow{}
	for rows.Next() {
		var i ListActiveAlertesRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.CameraNom,
			&i.ZoneID,
			&i.ZoneNom,
			&i.TypeRisqueID,
			&i.TypeRisqueCode,
			&i.TypeRisqueNom,
			&i.TypeRisqueCouleur,
			&i.Severite,
			&i.Description,
			&i.DetailsIa,
			&i.Confiance,
			&i.ImageUrl,
			&i.Statut,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertes = `-- name: ListAlertes :many
SELECT 
    a.id,
    a.camera_id,
    c.nom as camera_nom,
    a.zone_id,
    z.nom as zone_nom,
    a.type_risque_id,
    tr.code as type_risque_code,
    tr.nom as type_risque_nom,
    tr.couleur as type_risque_couleur,
    a.severite,
    a.description,
    a.details_ia,
    a.confiance,
    a.image_url,
    a.statut,
    a.acknowledged_at,
    a.resolved_at,
    a.notes,
    a.created_at
FROM alertes a
LEFT JOIN cameras c ON a.camera_id = c.id
LEFT JOIN zones z ON a.zone_id = z.id
LEFT JOIN types_risque tr ON a.type_risque_id = tr.id
ORDER BY a.created_at DESC
LIMIT ?
`

type ListAlertesRow struct {
	ID                int64      `json:"id"`
	CameraID          *int64     `json:"camera_id"`
	CameraNom         *string    `json:"camera_nom"`
	ZoneID            *int64     `json:"zone_id"`
	ZoneNom           *string    `json:"zone_nom"`
	TypeRisqueID      *int64     `json:"type_risque_id"`
	TypeRisqueCode    *string    `json:"type_risque_code"`
	TypeRisqueNom     *string    `json:"type_risque_nom"`
	TypeRisqueCouleur *string    `json:"type_risque_couleur"`
	Severite          int64      `json:"severite"`
	Description       string     `json:"description"`
	DetailsIa         *string    `json:"details_ia"`
	Confiance         float64    `json:"confiance"`
	ImageUrl          *string    `json:"image_url"`
	Statut            string     `json:"statut"`
	AcknowledgedAt    *time.Time `json:"acknowledged_at"`
	ResolvedAt        *time.Time `json:"resolved_at"`
	Notes             *string    `json:"notes"`
	CreatedAt         time.Time  `json:"created_at"`
}

func (q *Queries) ListAlertes(ctx context.Context, limit int64) ([]ListAlertesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlertes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertesRow{}
	for rows.Next() {
		var i ListAlertesRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.CameraNom,
			&i.ZoneID,
			&i.ZoneNom,
			&i.TypeRisqueID,
			&i.TypeRisqueCode,
			&i.TypeRisqueNom,
			&i.TypeRisqueCouleur,
			&i.Severite,
			&i.Description,
			&i.DetailsIa,
			&i.Confiance,
			&i.ImageUrl,
			&i.Statut,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameras = `-- name: ListCameras :many
SELECT 
    c.id,
    c.nom,
    c.zone_id,
    z.nom as zone_nom,
    z.niveau_risque as zone_niveau_risque,
    c.emplacement,
    c.flux_url,
    c.statut,
    c.derniere_detection,
    c.created_at,
    (SELECT COUNT(*) FROM alertes WHERE camera_id = c.id AND statut = 'active') as alertes_actives
FROM cameras c
LEFT JOIN zones z ON c.zone_id = z.id
ORDER BY c.zone_id, c.nom
`

type ListCamerasRow struct {
	ID                int64      `json:"id"`
	Nom               string     `json:"nom"`
	ZoneID            *int64     `json:"zone_id"`
	ZoneNom           *string    `json:"zone_nom"`
	ZoneNiveauRisque  *string    `json:"zone_niveau_risque"`
	Emplacement       *string    `json:"emplacement"`
	FluxUrl           *string    `json:"flux_url"`
	Statut            string     `json:"statut"`
	DerniereDetection *time.Time `json:"derniere_detection"`
	CreatedAt         time.Time  `json:"created_at"`
	AlertesActives    int64      `json:"alertes_actives"`
}

func (q *Queries) ListCameras(ctx context.Context) ([]ListCamerasRow, error) {
	rows, err := q.db.QueryContext(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCamerasRow{}
	for rows.Next() {
		var i ListCamerasRow
		if err := rows.Scan(
			&i.ID,
			&i.Nom,
			&i.ZoneID,
			&i.ZoneNom,
			&i.ZoneNiveauRisque,
			&i.Emplacement,
			&i.FluxUrl,
			&i.Statut,
			&i.DerniereDetection,
			&i.CreatedAt,
			&i.AlertesActives,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT 
    z.id,
    z.nom,
    z.description,
    z.niveau_risque,
    z.created_at,
    (SELECT COUNT(*) FROM cameras WHERE zone_id = z.id AND statut = 'active') as cameras_actives,
    (SELECT COUNT(*) FROM alertes WHERE zone_id = z.id AND statut = 'active') as alertes_actives
FROM zones z
ORDER BY 
    CASE z.niveau_risque 
        WHEN 'critique' THEN 1 
        WHEN 'eleve' THEN 2 
        WHEN 'moyen' THEN 3 
        ELSE 4 
    END
`

type ListZonesRow struct {
	ID             int64     `json:"id"`
	Nom            string    `json:"nom"`
	Description    *string   `json:"description"`
	NiveauRisque   string    `json:"niveau_risque"`
	CreatedAt      time.Time `json:"created_at"`
	CamerasActives int64     `json:"cameras_actives"`
	AlertesActives int64     `json:"alertes_actives"`
}

func (q *Queries) ListZones(ctx context.Context) ([]ListZonesRow, error) {
	rows, err := q.db.QueryContext(ctx, listZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nom,
			&i.Description,
			&i.NiveauRisque,
			&i.CreatedAt,
			&i.CamerasActives,
			&i.AlertesActives,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlerte = `-- name: ResolveAlerte :exec
UPDATE alertes SET statut = 'resolved', resolved_at = ?, notes = ? WHERE id = ?
`

type ResolveAlerteParams struct {
	ResolvedAt *time.Time `json:"resolved_at"`
	Notes      *string    `json:"notes"`
	ID         int64      `json:"id"`
}

func (q *Queries) ResolveAlerte(ctx context.Context, arg ResolveAlerteParams) error {
	_, err := q.db.ExecContext(ctx, resolveAlerte, arg.ResolvedAt, arg.Notes, arg.ID)
	return err
}
