// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: securite.sql

package dbgen

import (
	"context"
	"time"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :exec
UPDATE alerts SET status = 'acknowledged', acknowledged_at = ? WHERE id = ?
`

type AcknowledgeAlertParams struct {
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	ID             int64      `json:"id"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAlert, arg.AcknowledgedAt, arg.ID)
	return err
}

const assignRole = `-- name: AssignRole :exec
INSERT OR IGNORE INTO user_roles (user_id, role_id) VALUES (?, ?)
`

type AssignRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const closeAlert = `-- name: CloseAlert :exec
UPDATE alerts SET status = 'closed' WHERE id = ?
`

func (q *Queries) CloseAlert(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, closeAlert, id)
	return err
}

const countActiveAlerts = `-- name: CountActiveAlerts :one
SELECT COUNT(*) FROM alerts WHERE status = 'new'
`

// Stats
func (q *Queries) CountActiveAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAlerts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveCameras = `-- name: CountActiveCameras :one
SELECT COUNT(*) FROM cameras
`

func (q *Queries) CountActiveCameras(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCameras)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAlertsToday = `-- name: CountAlertsToday :one
SELECT COUNT(*) FROM alerts WHERE date(sent_at) = date('now')
`

func (q *Queries) CountAlertsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAlertsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDetectionsToday = `-- name: CountDetectionsToday :one
SELECT COUNT(*) FROM detections WHERE date(timestamp) = date('now')
`

// Detections (for stats)
func (q *Queries) CountDetectionsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDetectionsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countHighRiskZones = `-- name: CountHighRiskZones :one
SELECT COUNT(*) FROM zones WHERE risk_level = 'HIGH' AND is_active = 1
`

func (q *Queries) CountHighRiskZones(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countHighRiskZones)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCamera = `-- name: CreateCamera :one
INSERT INTO cameras (plan_id, name, stream_url, x_plan, y_plan, orientation, fov, is_webcam) 
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, plan_id, name, stream_url, x_plan, y_plan, orientation, fov, calibration_matrix, confidence_config, is_webcam, created_at
`

type CreateCameraParams struct {
	PlanID      *int64   `json:"plan_id"`
	Name        *string  `json:"name"`
	StreamUrl   *string  `json:"stream_url"`
	XPlan       *float64 `json:"x_plan"`
	YPlan       *float64 `json:"y_plan"`
	Orientation *float64 `json:"orientation"`
	Fov         *float64 `json:"fov"`
	IsWebcam    *int64   `json:"is_webcam"`
}

func (q *Queries) CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error) {
	row := q.db.QueryRowContext(ctx, createCamera,
		arg.PlanID,
		arg.Name,
		arg.StreamUrl,
		arg.XPlan,
		arg.YPlan,
		arg.Orientation,
		arg.Fov,
		arg.IsWebcam,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.StreamUrl,
		&i.XPlan,
		&i.YPlan,
		&i.Orientation,
		&i.Fov,
		&i.CalibrationMatrix,
		&i.ConfidenceConfig,
		&i.IsWebcam,
		&i.CreatedAt,
	)
	return i, err
}

const createHSERule = `-- name: CreateHSERule :one
INSERT INTO hse_rules (name, description, condition_logic, severity, is_active) 
VALUES (?, ?, ?, ?, ?) RETURNING id, name, description, condition_logic, severity, is_active
`

type CreateHSERuleParams struct {
	Name           *string `json:"name"`
	Description    *string `json:"description"`
	ConditionLogic *string `json:"condition_logic"`
	Severity       *int64  `json:"severity"`
	IsActive       *int64  `json:"is_active"`
}

func (q *Queries) CreateHSERule(ctx context.Context, arg CreateHSERuleParams) (HseRule, error) {
	row := q.db.QueryRowContext(ctx, createHSERule,
		arg.Name,
		arg.Description,
		arg.ConditionLogic,
		arg.Severity,
		arg.IsActive,
	)
	var i HseRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConditionLogic,
		&i.Severity,
		&i.IsActive,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO models (name, type, version, metrics, is_active) VALUES (?, ?, ?, ?, ?) RETURNING id, name, type, version, trained_at, metrics, is_active
`

type CreateModelParams struct {
	Name     *string `json:"name"`
	Type     *string `json:"type"`
	Version  *string `json:"version"`
	Metrics  *string `json:"metrics"`
	IsActive *int64  `json:"is_active"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, createModel,
		arg.Name,
		arg.Type,
		arg.Version,
		arg.Metrics,
		arg.IsActive,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.TrainedAt,
		&i.Metrics,
		&i.IsActive,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (site_id, level, image_path, scale_factor) VALUES (?, ?, ?, ?) RETURNING id, site_id, level, image_path, scale_factor, created_at
`

type CreatePlanParams struct {
	SiteID      *int64   `json:"site_id"`
	Level       *string  `json:"level"`
	ImagePath   *string  `json:"image_path"`
	ScaleFactor *float64 `json:"scale_factor"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.SiteID,
		arg.Level,
		arg.ImagePath,
		arg.ScaleFactor,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Level,
		&i.ImagePath,
		&i.ScaleFactor,
		&i.CreatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (name, location, description) VALUES (?, ?, ?) RETURNING id, name, location, description, confidence_config, created_at
`

type CreateSiteParams struct {
	Name        string  `json:"name"`
	Location    *string `json:"location"`
	Description *string `json:"description"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, createSite, arg.Name, arg.Location, arg.Description)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.ConfidenceConfig,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, is_active) VALUES (?, ?, ?, 1) RETURNING id, username, email, password_hash, is_active, created_at, last_login
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (plan_id, name, type, polygon, risk_level, is_active) 
VALUES (?, ?, ?, ?, ?, 1) RETURNING id, plan_id, name, type, polygon, risk_level, is_active, created_at
`

type CreateZoneParams struct {
	PlanID    *int64  `json:"plan_id"`
	Name      *string `json:"name"`
	Type      *string `json:"type"`
	Polygon   string  `json:"polygon"`
	RiskLevel *string `json:"risk_level"`
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRowContext(ctx, createZone,
		arg.PlanID,
		arg.Name,
		arg.Type,
		arg.Polygon,
		arg.RiskLevel,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Type,
		&i.Polygon,
		&i.RiskLevel,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCamera = `-- name: DeleteCamera :exec
DELETE FROM cameras WHERE id = ?
`

func (q *Queries) DeleteCamera(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCamera, id)
	return err
}

const deleteHSERule = `-- name: DeleteHSERule :exec
DELETE FROM hse_rules WHERE id = ?
`

func (q *Queries) DeleteHSERule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHSERule, id)
	return err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = ?
`

func (q *Queries) DeleteModel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = ?
`

func (q *Queries) DeleteSite(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSite, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteZone = `-- name: DeleteZone :exec
UPDATE zones SET is_active = 0 WHERE id = ?
`

func (q *Queries) DeleteZone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const getCamera = `-- name: GetCamera :one
SELECT id, plan_id, name, stream_url, x_plan, y_plan, orientation, fov, calibration_matrix, confidence_config, is_webcam, created_at FROM cameras WHERE id = ?
`

func (q *Queries) GetCamera(ctx context.Context, id int64) (Camera, error) {
	row := q.db.QueryRowContext(ctx, getCamera, id)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.StreamUrl,
		&i.XPlan,
		&i.YPlan,
		&i.Orientation,
		&i.Fov,
		&i.CalibrationMatrix,
		&i.ConfidenceConfig,
		&i.IsWebcam,
		&i.CreatedAt,
	)
	return i, err
}

const getHSERule = `-- name: GetHSERule :one
SELECT id, name, description, condition_logic, severity, is_active FROM hse_rules WHERE id = ?
`

func (q *Queries) GetHSERule(ctx context.Context, id int64) (HseRule, error) {
	row := q.db.QueryRowContext(ctx, getHSERule, id)
	var i HseRule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ConditionLogic,
		&i.Severity,
		&i.IsActive,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, name, type, version, trained_at, metrics, is_active FROM models WHERE id = ?
`

func (q *Queries) GetModel(ctx context.Context, id int64) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Version,
		&i.TrainedAt,
		&i.Metrics,
		&i.IsActive,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, site_id, level, image_path, scale_factor, created_at FROM plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id int64) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Level,
		&i.ImagePath,
		&i.ScaleFactor,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentDetections = `-- name: GetRecentDetections :many
SELECT d.id, d.camera_id, d.timestamp, d.object_class, d.confidence, d.bbox_x, d.bbox_y, d.bbox_w, d.bbox_h, d.track_id, c.name as camera_name 
FROM detections d
LEFT JOIN cameras c ON d.camera_id = c.id
ORDER BY d.timestamp DESC
LIMIT ?
`

type GetRecentDetectionsRow struct {
	ID          int64     `json:"id"`
	CameraID    *int64    `json:"camera_id"`
	Timestamp   time.Time `json:"timestamp"`
	ObjectClass *string   `json:"object_class"`
	Confidence  *float64  `json:"confidence"`
	BboxX       *float64  `json:"bbox_x"`
	BboxY       *float64  `json:"bbox_y"`
	BboxW       *float64  `json:"bbox_w"`
	BboxH       *float64  `json:"bbox_h"`
	TrackID     *int64    `json:"track_id"`
	CameraName  *string   `json:"camera_name"`
}

func (q *Queries) GetRecentDetections(ctx context.Context, limit int64) ([]GetRecentDetectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentDetections, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentDetectionsRow{}
	for rows.Next() {
		var i GetRecentDetectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.Timestamp,
			&i.ObjectClass,
			&i.Confidence,
			&i.BboxX,
			&i.BboxY,
			&i.BboxW,
			&i.BboxH,
			&i.TrackID,
			&i.CameraName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSite = `-- name: GetSite :one
SELECT id, name, location, description, confidence_config, created_at FROM sites WHERE id = ?
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Location,
		&i.Description,
		&i.ConfidenceConfig,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, is_active, created_at, last_login FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_active, created_at, last_login FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getZone = `-- name: GetZone :one
SELECT id, plan_id, name, type, polygon, risk_level, is_active, created_at FROM zones WHERE id = ?
`

func (q *Queries) GetZone(ctx context.Context, id int64) (Zone, error) {
	row := q.db.QueryRowContext(ctx, getZone, id)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Name,
		&i.Type,
		&i.Polygon,
		&i.RiskLevel,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAlerts = `-- name: ListActiveAlerts :many
SELECT a.id, a.risk_event_id, a.alert_level, a.status, a.sent_at, a.acknowledged_at, re.risk_score, re.risk_level as event_risk_level, re.explanation,
       z.name as zone_name, hr.name as rule_name
FROM alerts a
LEFT JOIN risk_events re ON a.risk_event_id = re.id
LEFT JOIN zones z ON re.zone_id = z.id
LEFT JOIN hse_rules hr ON re.rule_id = hr.id
WHERE a.status = 'new'
ORDER BY a.sent_at DESC
`

type ListActiveAlertsRow struct {
	ID             int64      `json:"id"`
	RiskEventID    *int64     `json:"risk_event_id"`
	AlertLevel     *string    `json:"alert_level"`
	Status         *string    `json:"status"`
	SentAt         time.Time  `json:"sent_at"`
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	RiskScore      *float64   `json:"risk_score"`
	EventRiskLevel *string    `json:"event_risk_level"`
	Explanation    *string    `json:"explanation"`
	ZoneName       *string    `json:"zone_name"`
	RuleName       *string    `json:"rule_name"`
}

func (q *Queries) ListActiveAlerts(ctx context.Context) ([]ListActiveAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAlertsRow{}
	for rows.Next() {
		var i ListActiveAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.RiskEventID,
			&i.AlertLevel,
			&i.Status,
			&i.SentAt,
			&i.AcknowledgedAt,
			&i.RiskScore,
			&i.EventRiskLevel,
			&i.Explanation,
			&i.ZoneName,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.risk_event_id, a.alert_level, a.status, a.sent_at, a.acknowledged_at, re.risk_score, re.risk_level as event_risk_level, re.explanation,
       z.name as zone_name, hr.name as rule_name
FROM alerts a
LEFT JOIN risk_events re ON a.risk_event_id = re.id
LEFT JOIN zones z ON re.zone_id = z.id
LEFT JOIN hse_rules hr ON re.rule_id = hr.id
ORDER BY a.sent_at DESC
LIMIT ?
`

type ListAlertsRow struct {
	ID             int64      `json:"id"`
	RiskEventID    *int64     `json:"risk_event_id"`
	AlertLevel     *string    `json:"alert_level"`
	Status         *string    `json:"status"`
	SentAt         time.Time  `json:"sent_at"`
	AcknowledgedAt *time.Time `json:"acknowledged_at"`
	RiskScore      *float64   `json:"risk_score"`
	EventRiskLevel *string    `json:"event_risk_level"`
	Explanation    *string    `json:"explanation"`
	ZoneName       *string    `json:"zone_name"`
	RuleName       *string    `json:"rule_name"`
}

// Alerts
func (q *Queries) ListAlerts(ctx context.Context, limit int64) ([]ListAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlerts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.RiskEventID,
			&i.AlertLevel,
			&i.Status,
			&i.SentAt,
			&i.AcknowledgedAt,
			&i.RiskScore,
			&i.EventRiskLevel,
			&i.Explanation,
			&i.ZoneName,
			&i.RuleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameras = `-- name: ListCameras :many
SELECT c.id, c.plan_id, c.name, c.stream_url, c.x_plan, c.y_plan, c.orientation, c.fov, c.calibration_matrix, c.confidence_config, c.is_webcam, c.created_at, p.level as plan_level, s.name as site_name 
FROM cameras c 
LEFT JOIN plans p ON c.plan_id = p.id 
LEFT JOIN sites s ON p.site_id = s.id 
ORDER BY s.name, p.level, c.name
`

type ListCamerasRow struct {
	ID                int64     `json:"id"`
	PlanID            *int64    `json:"plan_id"`
	Name              *string   `json:"name"`
	StreamUrl         *string   `json:"stream_url"`
	XPlan             *float64  `json:"x_plan"`
	YPlan             *float64  `json:"y_plan"`
	Orientation       *float64  `json:"orientation"`
	Fov               *float64  `json:"fov"`
	CalibrationMatrix *string   `json:"calibration_matrix"`
	ConfidenceConfig  *string   `json:"confidence_config"`
	IsWebcam          *int64    `json:"is_webcam"`
	CreatedAt         time.Time `json:"created_at"`
	PlanLevel         *string   `json:"plan_level"`
	SiteName          *string   `json:"site_name"`
}

// Cameras
func (q *Queries) ListCameras(ctx context.Context) ([]ListCamerasRow, error) {
	rows, err := q.db.QueryContext(ctx, listCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCamerasRow{}
	for rows.Next() {
		var i ListCamerasRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.StreamUrl,
			&i.XPlan,
			&i.YPlan,
			&i.Orientation,
			&i.Fov,
			&i.CalibrationMatrix,
			&i.ConfidenceConfig,
			&i.IsWebcam,
			&i.CreatedAt,
			&i.PlanLevel,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamerasByPlan = `-- name: ListCamerasByPlan :many
SELECT id, plan_id, name, stream_url, x_plan, y_plan, orientation, fov, calibration_matrix, confidence_config, is_webcam, created_at FROM cameras WHERE plan_id = ? ORDER BY name
`

func (q *Queries) ListCamerasByPlan(ctx context.Context, planID *int64) ([]Camera, error) {
	rows, err := q.db.QueryContext(ctx, listCamerasByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.StreamUrl,
			&i.XPlan,
			&i.YPlan,
			&i.Orientation,
			&i.Fov,
			&i.CalibrationMatrix,
			&i.ConfidenceConfig,
			&i.IsWebcam,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHSERules = `-- name: ListHSERules :many
SELECT id, name, description, condition_logic, severity, is_active FROM hse_rules ORDER BY severity DESC, name
`

// HSE Rules
func (q *Queries) ListHSERules(ctx context.Context) ([]HseRule, error) {
	rows, err := q.db.QueryContext(ctx, listHSERules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HseRule{}
	for rows.Next() {
		var i HseRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ConditionLogic,
			&i.Severity,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, name, type, version, trained_at, metrics, is_active FROM models ORDER BY name, version DESC
`

// Models
func (q *Queries) ListModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Version,
			&i.TrainedAt,
			&i.Metrics,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT p.id, p.site_id, p.level, p.image_path, p.scale_factor, p.created_at, s.name as site_name FROM plans p LEFT JOIN sites s ON p.site_id = s.id ORDER BY s.name, p.level
`

type ListPlansRow struct {
	ID          int64     `json:"id"`
	SiteID      *int64    `json:"site_id"`
	Level       *string   `json:"level"`
	ImagePath   *string   `json:"image_path"`
	ScaleFactor *float64  `json:"scale_factor"`
	CreatedAt   time.Time `json:"created_at"`
	SiteName    *string   `json:"site_name"`
}

// Plans
func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlansRow{}
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Level,
			&i.ImagePath,
			&i.ScaleFactor,
			&i.CreatedAt,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansBySite = `-- name: ListPlansBySite :many
SELECT id, site_id, level, image_path, scale_factor, created_at FROM plans WHERE site_id = ? ORDER BY level
`

func (q *Queries) ListPlansBySite(ctx context.Context, siteID *int64) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlansBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Level,
			&i.ImagePath,
			&i.ScaleFactor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at FROM roles ORDER BY name
`

// Roles
func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, name, location, description, confidence_config, created_at FROM sites ORDER BY name
`

// Sites
func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Description,
			&i.ConfidenceConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.username, u.email, u.password_hash, u.is_active, u.created_at, u.last_login, GROUP_CONCAT(r.name) as roles
FROM users u 
LEFT JOIN user_roles ur ON u.id = ur.user_id 
LEFT JOIN roles r ON ur.role_id = r.id
GROUP BY u.id
ORDER BY u.username
`

type ListUsersRow struct {
	ID           int64      `json:"id"`
	Username     string     `json:"username"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	IsActive     *int64     `json:"is_active"`
	CreatedAt    time.Time  `json:"created_at"`
	LastLogin    *time.Time `json:"last_login"`
	Roles        string     `json:"roles"`
}

// Users
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.LastLogin,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZones = `-- name: ListZones :many
SELECT z.id, z.plan_id, z.name, z.type, z.polygon, z.risk_level, z.is_active, z.created_at, p.level as plan_level, s.name as site_name 
FROM zones z 
LEFT JOIN plans p ON z.plan_id = p.id 
LEFT JOIN sites s ON p.site_id = s.id 
WHERE z.is_active = 1
ORDER BY s.name, p.level, z.name
`

type ListZonesRow struct {
	ID        int64     `json:"id"`
	PlanID    *int64    `json:"plan_id"`
	Name      *string   `json:"name"`
	Type      *string   `json:"type"`
	Polygon   string    `json:"polygon"`
	RiskLevel *string   `json:"risk_level"`
	IsActive  *int64    `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	PlanLevel *string   `json:"plan_level"`
	SiteName  *string   `json:"site_name"`
}

// Zones
func (q *Queries) ListZones(ctx context.Context) ([]ListZonesRow, error) {
	rows, err := q.db.QueryContext(ctx, listZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListZonesRow{}
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Type,
			&i.Polygon,
			&i.RiskLevel,
			&i.IsActive,
			&i.CreatedAt,
			&i.PlanLevel,
			&i.SiteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesByPlan = `-- name: ListZonesByPlan :many
SELECT id, plan_id, name, type, polygon, risk_level, is_active, created_at FROM zones WHERE plan_id = ? AND is_active = 1 ORDER BY name
`

func (q *Queries) ListZonesByPlan(ctx context.Context, planID *int64) ([]Zone, error) {
	rows, err := q.db.QueryContext(ctx, listZonesByPlan, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Zone{}
	for rows.Next() {
		var i Zone
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Name,
			&i.Type,
			&i.Polygon,
			&i.RiskLevel,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRole = `-- name: RemoveRole :exec
DELETE FROM user_roles WHERE user_id = ? AND role_id = ?
`

type RemoveRoleParams struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

func (q *Queries) RemoveRole(ctx context.Context, arg RemoveRoleParams) error {
	_, err := q.db.ExecContext(ctx, removeRole, arg.UserID, arg.RoleID)
	return err
}

const updateCamera = `-- name: UpdateCamera :exec
UPDATE cameras SET plan_id = ?, name = ?, stream_url = ?, x_plan = ?, y_plan = ?, orientation = ?, fov = ?, is_webcam = ? WHERE id = ?
`

type UpdateCameraParams struct {
	PlanID      *int64   `json:"plan_id"`
	Name        *string  `json:"name"`
	StreamUrl   *string  `json:"stream_url"`
	XPlan       *float64 `json:"x_plan"`
	YPlan       *float64 `json:"y_plan"`
	Orientation *float64 `json:"orientation"`
	Fov         *float64 `json:"fov"`
	IsWebcam    *int64   `json:"is_webcam"`
	ID          int64    `json:"id"`
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) error {
	_, err := q.db.ExecContext(ctx, updateCamera,
		arg.PlanID,
		arg.Name,
		arg.StreamUrl,
		arg.XPlan,
		arg.YPlan,
		arg.Orientation,
		arg.Fov,
		arg.IsWebcam,
		arg.ID,
	)
	return err
}

const updateHSERule = `-- name: UpdateHSERule :exec
UPDATE hse_rules SET name = ?, description = ?, condition_logic = ?, severity = ?, is_active = ? WHERE id = ?
`

type UpdateHSERuleParams struct {
	Name           *string `json:"name"`
	Description    *string `json:"description"`
	ConditionLogic *string `json:"condition_logic"`
	Severity       *int64  `json:"severity"`
	IsActive       *int64  `json:"is_active"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateHSERule(ctx context.Context, arg UpdateHSERuleParams) error {
	_, err := q.db.ExecContext(ctx, updateHSERule,
		arg.Name,
		arg.Description,
		arg.ConditionLogic,
		arg.Severity,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateModel = `-- name: UpdateModel :exec
UPDATE models SET name = ?, type = ?, version = ?, metrics = ?, is_active = ? WHERE id = ?
`

type UpdateModelParams struct {
	Name     *string `json:"name"`
	Type     *string `json:"type"`
	Version  *string `json:"version"`
	Metrics  *string `json:"metrics"`
	IsActive *int64  `json:"is_active"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.ExecContext(ctx, updateModel,
		arg.Name,
		arg.Type,
		arg.Version,
		arg.Metrics,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET site_id = ?, level = ?, image_path = ?, scale_factor = ? WHERE id = ?
`

type UpdatePlanParams struct {
	SiteID      *int64   `json:"site_id"`
	Level       *string  `json:"level"`
	ImagePath   *string  `json:"image_path"`
	ScaleFactor *float64 `json:"scale_factor"`
	ID          int64    `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.SiteID,
		arg.Level,
		arg.ImagePath,
		arg.ScaleFactor,
		arg.ID,
	)
	return err
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET name = ?, location = ?, description = ? WHERE id = ?
`

type UpdateSiteParams struct {
	Name        string  `json:"name"`
	Location    *string `json:"location"`
	Description *string `json:"description"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.ExecContext(ctx, updateSite,
		arg.Name,
		arg.Location,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET username = ?, email = ?, is_active = ? WHERE id = ?
`

type UpdateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	IsActive *int64 `json:"is_active"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateZone = `-- name: UpdateZone :exec
UPDATE zones SET plan_id = ?, name = ?, type = ?, polygon = ?, risk_level = ?, is_active = ? WHERE id = ?
`

type UpdateZoneParams struct {
	PlanID    *int64  `json:"plan_id"`
	Name      *string `json:"name"`
	Type      *string `json:"type"`
	Polygon   string  `json:"polygon"`
	RiskLevel *string `json:"risk_level"`
	IsActive  *int64  `json:"is_active"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) error {
	_, err := q.db.ExecContext(ctx, updateZone,
		arg.PlanID,
		arg.Name,
		arg.Type,
		arg.Polygon,
		arg.RiskLevel,
		arg.IsActive,
		arg.ID,
	)
	return err
}
